import { Link, useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppHeader } from '@/components/AppHeader';
import { DRILLS } from '@/lib/drills';
import { getDrillHistory, isHistoryUserSignedIn } from '@/lib/progress';

export default function HistoryScreen(){const [rows,setRows]=useState<Array<{date:string;seconds:number;sentences:number;drills:string[]}>>([]);const [isSignedIn,setIsSignedIn]=useState(false);useFocusEffect(useCallback(()=>{Promise.all([isHistoryUserSignedIn(),getDrillHistory()]).then(([signedIn,entries])=>{setIsSignedIn(signedIn);const grouped=new Map<string,{date:string;seconds:number;sentences:number;drills:string[]}>();entries.forEach((entry)=>{const row=grouped.get(entry.date)??{date:entry.date,seconds:0,sentences:0,drills:[]};row.seconds+=entry.durationSeconds;row.sentences+=entry.sentenceCount;if(!row.drills.includes(entry.drillId))row.drills.push(entry.drillId);grouped.set(entry.date,row)});setRows(Array.from(grouped.values()).reverse())}).catch(()=>{setIsSignedIn(false);setRows([])})},[]));return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}><AppHeader /><Text style={styles.title}>発話の履歴</Text><Text style={styles.note}>取り組んだ時間と例文数を日ごとに確認できます。</Text>{!isSignedIn?<View style={styles.empty}><Text style={styles.emptyTitle}>ログインすると練習記録を残せます</Text><Text style={styles.note}>ドリルはログインなしでもお試しいただけます。履歴はログイン後の練習から保存されます。</Text></View>:rows.length===0?<View style={styles.empty}><Text style={styles.emptyTitle}>まだ記録がありません</Text><Text style={styles.note}>最初のドリルを1文読んでみましょう。</Text><Link href="/drills" style={styles.link}>ドリルを始める</Link></View>:<View style={styles.list}>{rows.map((row)=><View key={row.date} style={styles.row}><View><Text style={styles.date}>{row.date}</Text><Text style={styles.drills}>{row.drills.map((id)=>DRILLS.find((d)=>d.id===id)?.shortTitle).filter(Boolean).join('・')}</Text></View><Text style={styles.value}>{Math.max(1,Math.round(row.seconds/60))}分・{row.sentences}文</Text></View>)}</View>}</ScrollView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F6F3EC'},container:{width:'100%',maxWidth:720,alignSelf:'center',padding:22},back:{color:'#187A64',fontSize:13,fontWeight:'700'},title:{color:'#19312D',fontSize:28,fontWeight:'800',marginTop:22},note:{color:'#60726E',fontSize:13,lineHeight:21,marginTop:6},empty:{backgroundColor:'#FFF',borderRadius:20,padding:24,marginTop:22,alignItems:'center'},emptyTitle:{color:'#19312D',fontSize:17,fontWeight:'800'},link:{color:'#187A64',fontSize:13,fontWeight:'800',marginTop:15},list:{gap:9,marginTop:20},row:{backgroundColor:'#FFF',borderRadius:16,padding:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},date:{color:'#19312D',fontSize:14,fontWeight:'800'},drills:{color:'#60726E',fontSize:11,marginTop:4},value:{color:'#0F5E4D',fontSize:14,fontWeight:'800'}});
